### PR TITLE
Fix renovate.json

### PR DESCRIPTION
**Pull request by rarkins**

### CODE REVIEW

**Comment by abraham** [comment]
Thanks! I'd noticed a lack of PRs but hadn't looked into it yet.

**Comment by rarkins** [comment]
Normally Renovate raises issues to earn about config errors but looks like they’re disabled for this repo?

**Comment by abraham** [comment]
I want to manage all the issues in the parent [abraham/nutmeg-cli](https://github.com/abraham/nutmeg-cli) repo. Maybe Renovate should take into account the `bugs` value in [package.json](https://github.com/abraham/nutmeg-seed/blob/master/package.json#L43)?

**Comment by rarkins** [comment]
I think I'll handle them manually for now, as this is the only case it's used and is the only time it's happened :)

**Pull request merged**
